# Generated by Django 5.0.6 on 2025-11-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'General User', 'verbose_name_plural': 'General Users'},
        ),
        migrations.AlterModelOptions(
            name='userpet',
            options={'verbose_name': 'UserPet', 'verbose_name_plural': 'UserPets'},
        ),
        migrations.AlterModelOptions(
            name='uservet',
            options={'verbose_name': 'UserVet', 'verbose_name_plural': 'UserVets'},
        ),
        migrations.AddField(
            model_name='uservet',
            name='recibir_emergencias',
            field=models.BooleanField(default=False),
        ),
    ]
