# Generated by Django 5.2 on 2025-11-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0002_alter_user_options_alter_userpet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservet',
            name='años_experiencia',
            field=models.IntegerField(blank=True, help_text='Años de experiencia profesional', null=True),
        ),
    ]
