# Generated by Django 5.2.5 on 2025-10-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0005_veterinario_especializacion_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favoritos_de', to='vet.veterinario'),
        ),
    ]
